
- hosts: webserver
  become: true
  tasks:
     - name: install web server
       apt:
          name: {{ item }}
          state: present
          update_cache: yes
       with_items: 
             - apache2
             - python-pip
             - python-virtualenv
             - libapache2-mod-wsgi

